POST http://localhost/counter/counters/1/increase/
Content-Type: application/json

{
  "increase_value": 10
}

###

POST http://localhost:8000/counter/counters/1/increase/
Content-Type: application/json

{
  "increase_value": 10
}

###

POST http://localhost:8000/counter/counters/1/decrease/
Content-Type: application/json

{
  "decrease_value": 10
}

###

POST http://127.0.0.1:8000/api/v1/widgets/
Content-Type: application/json

{
  "title": "test1"
}